---
- name: "Base development config"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-cli"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot-nightly
            - snyk-security.snyk-vulnerability-scanner
